- fuel/modules/fuel/config/fuel.php
- fuel/modules/fuel/config/fuel_hooks.php
- fuel/modules/fuel/hooks/Fuel_hooks.php
* Updated the sequence of offline & dev_password being evaluated.
* Updated offline maintenance page doesn't required dev_password.
* Updated Fuel_hooks.offline to redirect to 'offline' page instead of rendering offline content.
* Added fuel config constant 'offline_allowed_uri' indicates pages allowed to access in offline mode.
> Updated offline and development password mode.

- fuel/modules/fuel/core/Router.php
I spotted some issues while I was debugging something else.
If you have a config item 'controller_suffix' it will be applied twice to the `$class` var. This is because it is concatenated once on the Fuel_Router and again in the MX_Router.
```
public function set_class($class)
{
$class = $class.$this->config->item('controller_suffix');
parent::set_class($class);
}
```
MX_Router::set_class() (line 236)
Also in the Fuel_Router there is a var called `$located`. This is a private var in the MX_Router class and is not explicitly defined at the top of the Fuel_Router class. This was not causing any code execution issues but it was showing as an error in my IDE because it was not defined.
> Issues spotted while debugging

- fuel/modules/fuel/core/MY_DB_mysqli_driver.php
This prevents errors when the selected database's name has characters such as dashes in it.
I noticed the `MY_DB_mysql_driver` class already uses back-ticks, but the `MY_DB_mysqli_driver` class does not.
- Create a database with a dash in the name, e.g. `foo-bar`.
- Set up FUEL-CMS, updating the `database.php` file with database details, leaving `mysqli` as the `dbdriver`.
- Generate a simple model `baz` to invoke the driver.
```
C:\wamp64\www\FUEL-CMS>php index.php fuel/generate/simple baz
Database error: A Database Error Occurred
Error Number: 1064
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-bar' at line 1
USE foo-bar
Filename: C:/wamp64/www/FUEL-CMS/fuel/modules/fuel/core/MY_DB_mysqli_driver.php …
```
> Surround database name with ticks in USE statement in the MySQLi driver

- fuel/modules/fuel/views/_generate/advanced/libraries/Fuel_{module}.php
This fixes an 'Incompatible declaration' error when accessing a generated advanced module.
1. Generate an advanced module `foo` by running `php index.php fuel/generate/advanced foo`.
2. Navigate to anywhere the module is initialized, for example the user guide at `<site_url>/fuel/site_docs`. The error should be visible where the module's documentation should be.
```
A PHP Error was encountered
Severity: Runtime Notice
Message: Declaration of Fuel_foo::initialize() should be compatible with Fuel_advanced_module::initialize($params = Array)
Filename: libraries/Fuel_foo.php
Line Number: 61
Backtrace:
File: C:\wamp64\www\FUEL-CMS\fuel\modules\fuel\core\Loader.php
Line: 585
Function: _error_handler
File: C:\wamp64\www\FUEL-CMS\fuel\modules\fuel\core\Loader.php
Line: 585
Function: …
```
> Fix incompatible function declaration in advanced module template

- fuel/modules/fuel/core/MY_Model.php
Adds no more than a PHPDoc for the `db` field in `MY_Model` class.
With this additional type information in place IDEs can help users with auto-completion.
See attached screenshot from PhpStorm below (before & after):
> Add a PHPDoc for the $db field in MY_Model

- fuel/modules/fuel/config/fuel_routes.php
If people enter "fuel" as an allowed module in `config.php`, they'll be met with infinite recursion.
It seems the framework doesn't have a centralised handler of config values at the moment, so nothing prevents people from putting 'fuel' there. I stumbled upon this as I was playing around with the CLI.
An easy fix is to just check the module name and skip loading its routes if it is the `fuel` module.
* add `fuel` to the allowed modules array:
```
$config['modules_allowed'] = array(
'user_guide',
'fuel',
);
```
* load any page
> Prevent infinite recursion if 'fuel' is specified as an allowed module

- fuel/modules/fuel/views/_generate/model/Events_model.php
- Incompatible function declaration does not match that of super class (`related_items`);
- Method `related_items` says it returns an array or string, but can return null, as well;
- Incorrect usage of `parse_str`. It is a `void` method and parses the first argument into the second.
> Fix several small issues with Events_model example file

- fuel/modules/fuel/core/Loader.php
I tried using `$this->CI->load->module_model` and noticed it ignores the `$module` parameter passed to it, looking up the model in the `fuel` advanced module instead of my custom one.
I dug around `Loader.php` and found a number of instances where the `$module` parameter is completely ignored by functions.
> Unused $module variables in Loader.php

- fuel/modules/fuel/helpers/google_helper.php
Found another rogue `parse_str` use where FUEL CMS attempts to get a value back, even though the function returns `void`.
`parse_str` instead writes the updated value into the second argument.
> Fix incorrect usage of 'parse_str' in Google helper

- fuel/modules/fuel/helpers/google_helper.php
When using the Google helper, if an address is specified, PHP blows up with an error:
```
A PHP Error was encountered
Severity: Notice
Message: Undefined variable: addr
Filename: helpers/google_helper.php
Line Number: 257
Backtrace:
File: C:\wamp64\www\fuelcms\fuel\modules\fuel\helpers\google_helper.php
Line: 257
Function: _error_handler
File: C:\wamp64\www\fuelcms\fuel\application\controllers\Site.php
Line: 32
Function: google_map_url
File: C:\wamp64\www\fuelcms\index.php
Line: 364
Function: require_once
```
FUEL CMS tries to append the supplied state to a non-existent `addr` variable.
Instead we want to keep attaching data to `$p['q']`.
> Google helper address fix

- fuel/modules/fuel/helpers/MY_array_helper.php
- fuel/modules/fuel/helpers/MY_date_helper.php
- fuel/modules/fuel/helpers/MY_directory_helper.php
- fuel/modules/fuel/helpers/MY_file_helper.php
- fuel/modules/fuel/helpers/MY_html_helper.php
- fuel/modules/fuel/helpers/MY_language_helper.php
- fuel/modules/fuel/helpers/MY_string_helper.php
- fuel/modules/fuel/helpers/MY_url_helper.php
- fuel/modules/fuel/helpers/ajax_helper.php
- fuel/modules/fuel/helpers/asset_helper.php
- fuel/modules/fuel/helpers/browser_helper.php
- fuel/modules/fuel/helpers/compatibility_helper.php
- fuel/modules/fuel/helpers/convert_helper.php
- fuel/modules/fuel/helpers/format_helper.php
- fuel/modules/fuel/helpers/fuel_helper.php
- fuel/modules/fuel/helpers/google_helper.php
- fuel/modules/fuel/helpers/scraper_helper.php
- fuel/modules/fuel/helpers/session_helper.php
- fuel/modules/fuel/helpers/simplepie_helper.php
- fuel/modules/fuel/helpers/social_helper.php
- fuel/modules/fuel/helpers/utility_helper.php
- fuel/modules/fuel/helpers/validator_helper.php
Moves the PHPDoc comments inside helper files so they appear inside the `if (!function_exists...)` checks.
This allows IDEs to link the PHPDocs to the functions. Developers can then be immediately notified by the IDE if they're using a helper function incorrectly (passing wrong parameters, etc).
Moreover, this helped me uncover some errors in the PHPDocs themselves.
Lastly, some missing delimiter comments `// -------` have been added.
Best to go through this MR commit by commit to better see what changed.
> Move helper function PHPDocs inside 'function_exists' checks to help IDEs

- fuel/modules/fuel/libraries/Cli.php
- fuel/modules/fuel/libraries/Fuel_base_library.php
The `input` function accepts two arguments, yet it's given two.
> Fix several functions called with too many parameters

- fuel/modules/fuel/helpers/asset_helper.php
Found another small bug in the `asset_helper`.
Test:
```php
$this->load->helper('asset');
var_dump(captcha_path('foo.txt', NULL, TRUE));
var_dump(captcha_path('foo.txt', NULL, FALSE));
```
Before:
```php
'/fuel-cms/assets/captchas/foo.txt'
'/fuel-cms/assets/captchas/foo.txt'
```
After:
```php
'http://localhost/fuel-cms/assets/captchas/foo.txt'
'/fuel-cms/assets/captchas/foo.txt'
```
> Fix 'asset_helper' not passing 'absolute' param to Asset library

- fuel/modules/fuel/tests/Asset_test.php
PHP 7.1.9.
Running tests in `Asset_test`, I get the following error:
```
Severity: Notice
Message: Array to string conversion
Filename: tests/Asset_test.php
Line Number: 42
```
This is documented in [the PHP manual](http://php.net/manual/en/migration70.incompatible.php), section "Changes to the handling of indirect variables, properties, and methods".
Other small issues:
- One of the tests didn't call `$this->run` meaning its name was formatted differently.
- That same test didn't report the correct test name.
> Fix PHP7 issues in Asset_test

- fuel/modules/fuel/libraries/Validator.php
- fuel/modules/fuel/models/Fuel_assets_model.php
`Fuel_assets_model` has a method `record_count`. Calling it results in the following error:
```
Type: Error
Message: Call to undefined function dir_files()
Filename: C:\wamp64\www\FUEL-CMSa\fuel\modules\fuel\models\Fuel_assets_model.php
```
`dir_files` doesn't seem to exist in any of the helper files, however there is a method with such a name in the `Fuel_assets` library.
After applying https://github.com/daylightstudio/FUEL-CMS/commit/5f8c6ac23d7c7333818cffdd7300af14451e1d15, the error was gone, however the result was '0' even though the "images" directory has a file in it. Turns out, the `record_count` function was giving `dir_files` an absolute path, which in turn called `assets_server_path` on it, resulting in a nonsense path.
> Missing function "dir_files"

- fuel/modules/fuel/models/Fuel_pages_model.php
If a page's location starts with `http`, it will not be found by FUEL CMS. Even if it is a local path such as "http_page".
To reproduce, set up a page in the CMS with a location of "http_test", and then try to view it.
> Fix FUEL not finding pages whose location starts with 'http'

- fuel/modules/fuel/helpers/format_helper.php
- fuel/modules/fuel/tests/Format_helper_test.php
**This change alters the API of `format_helper` a bit.** Let me know if you disagree with it and I can change it back :-)
I looked around other frameworks and often `NULL` values are interpreted as 0-value.
Currently the `currency` function's PhpDoc says it returns `string` though really it's `string|null`. This change makes sure it always returns a formatted currency value.
Also, tests!
> Unit test 'format_helper'

- fuel/modules/fuel/helpers/google_helper.php
- fuel/modules/fuel/tests/Format_helper_test.php
- fuel/modules/fuel/tests/Google_helper_test.php
`create_function` has been deprecated as of PHP 7.2.0.
There are a number of uses throughout FUEL CMS.
As they internally invoke `eval` it's a good idea to remove them as they're way slower than anonymous functions, and reduce readability (a lot of IDEs just parse their content as strings).
I set up some unit tests before applying the change to make sure nothing's changed.
> F google helper create function

- fuel/modules/fuel/views/_docs/general/opt-in-controllers.php
I wanted to grab a code snippet from the FUEL docs when setting up a Controller, and noticed it was missing a closing bracket.
> Add missing closing bracket in code example

- fuel/modules/fuel/helpers/validator_helper.php
* Fuel CMS requires [PHP 5.4 or greater](http://docs.getfuelcms.com/installation/requirements)
* filter_var along with the filters [was added in 5.2.0](http://php.net/manual/en/function.filter-var.php)
I think we can get rid of the complicated regex there and leave it up to PHP to decide whether an e-mail is valid.
> Force use of 'filter_var' (introduced in PHP 5.2.0) in Validator helper

- fuel/modules/fuel/tests/My_model_test.php
The `to_json` method in `MY_Model` takes all the fields, collects them into an array and runs it through `json_encode`.
The "id" and "role_id" are `int`s when they're passed to the JSON encoder. This causes one of the tests to fail.
This is the only broken `My_model_test` test.
> Fix broken 'to_json' test in 'My_model_test'

- fuel/modules/fuel/views/_docs/modules/simple.php
The require_once references a file with a lower-case name. This is not
allowed by CodeIgniter since version 3.0.
> Fix wrong case in 'require_once' statement in module documentation.

- fuel/application/views/_docs/index.php
- fuel/modules/fuel/views/_docs/general/forms.php
- fuel/modules/fuel/views/_docs/general/models.php
- fuel/modules/fuel/views/_docs/general/navigation.php
- fuel/modules/fuel/views/_docs/modules/tutorial.php
* `fuel/application/views/_docs/index.php`: Missing hash symbol means the string "sitevariables" was not acting as an ID.
* `fuel/modules/fuel/views/_docs/general/forms.php`: Typo in "langauge" meant the link was not clickable.
* `fuel/modules/fuel/views/_docs/general/models.php`: Triple 't' in the word "formattters".
* `fuel/modules/fuel/views/_docs/general/navigation.php`: ID "sidemenu" does not exist, should be "hdr_sidemenu". If you look at the same sentence, the other ID mentioned in it is "hdr_topmenu".
*  `fuel/modules/fuel/views/_docs/modules/tutorial.php`: ID "categories_module" does not exist and does not make sense there!
> Fix issues with HTML IDs in several documentation files

- fuel/modules/fuel/libraries/Inspection.php
PHP 7.2.0 displays warnings when NULL is passed to its 'count' function,
which is exactly what happens if the User Guide module tries rendering
a method with no arguments.
This commit fixes that by initializing the 'params' variable with an
empty array in the 'initialize' method.
> Initialize function parameters array in 'Inspection' class.

- fuel/modules/fuel/libraries/Fuel_advanced_module.php
This adds a missing 'return' statement in Fuel_advanced_module. Given
the way the 'web_path' method works, an extra slash had to be added
before 'assets'.
A debug statement at the end of `\Fuel_tester::__construct` now shows:
> C:/xampp/htdocs/FUEL-CMS/tester/assets/tester.css
As a bonus, the `has_css()` method now actually does what it's supposed to, rather than always returning `FALSE` (as it used to always be given NULL)!
> Return CSS path when 'css_path' function is called.

- fuel/modules/fuel/core/MY_Model.php
Constant `__CLASS__` must have two trailing underscores.
See http://php.net/manual/en/language.constants.predefined.php
> Add missing trailing underscore in PHP '__CLASS__' constant

- fuel/modules/fuel/libraries/Inspection.php
Looks like there is a missing `break;` statement in one in the cases in `Inspection_comment::description`. Without it, whenever "periods" is given to the method, `ucfirst` is run as well.
> Add missing 'break' statement in \Inspection_comment::description

- fuel/modules/fuel/core/MY_DB_mysql_driver.php
- fuel/modules/fuel/core/MY_DB_mysql_result.php
- fuel/modules/fuel/core/MY_DB_mysqli_driver.php
- fuel/modules/fuel/core/MY_DB_mysqli_result.php
- fuel/modules/fuel/core/Router.php
- fuel/modules/fuel/helpers/MY_array_helper.php
- fuel/modules/fuel/libraries/Cache.php
- fuel/modules/fuel/libraries/Curl.php
- fuel/modules/fuel/libraries/Data_table.php
- fuel/modules/fuel/libraries/Form_builder.php
- fuel/modules/fuel/libraries/Fuel.php
- fuel/modules/fuel/libraries/Fuel_advanced_module.php
- fuel/modules/fuel/libraries/Fuel_base_library.php
- fuel/modules/fuel/libraries/Fuel_parser.php
- fuel/modules/fuel/libraries/MY_Image_lib.php
- fuel/modules/fuel/models/Base_module_model.php
- fuel/modules/fuel/models/Fuel_pages_model.php
Most changes are just return value updates in PhpDocs.
Several (for example, the one in Router.php) make it so that a void method is not returned. The void method is called, and then a simple `return;` follows, to make it slightly less confusing.
> Fix various small PhpDoc issues related to return values

- fuel/modules/fuel/config/fuel_routes.php
Instead of @include, which suppresses all errors in the included file, check for file existence.
> Proper check for file existence

- fuel/application/views/_install.php
- fuel/modules/fuel/views/_docs/general/pages-variables.php
Updates the installation script and documentation. The case of "auto" is updated to match what is in some of the PHP comments (`MY_fuel` has a comment that says "_options are cms, views, and auto_"), and what is returned by methods such as `\Fuel_pages::mode`.
Yes this is a _tiny_ change. However, I have to keep reminding myself whether the case actually matters when setting up new sites. I see "AUTO" in the installation script, go to `MY_fuel` to update it, and then notice it says "auto" there!
Best to be consistent.
> 'auto' case

- fuel/modules/fuel/language/english/fuel_lang.php
Introduced in ffcbdb781175e8336706d74d171758e93d79c77d.
> Fix typo '$lange' => '$lang'

- fuel/modules/fuel/controllers/Assets.php
Added the upscale parameter from 3bdcfa17 as field to `Assets::inline_create()` so it works with `$field['type'] = 'asset'`
> Fix upscale in `Assets::inline_create()`

- fuel/modules/fuel/helpers/markdown_helper.php
Getting the following error accessing the login screen with a fresh installation.
PHP 7.4.6.
```
A PHP Error was encountered
Severity: 8192
Message: Array and string offset access syntax with curly braces is deprecated
Filename: helpers/markdown_helper.php
Line Number: 1564
Backtrace:
File: C:\xampp\htdocs\FUEL-CMS\fuel\application\third_party\MX\Modules.php
Line: 158
Function: _error_handler
File: C:\xampp\htdocs\FUEL-CMS\fuel\application\third_party\MX\Modules.php
Line: 158
Function: include_once
File: C:\xampp\htdocs\FUEL-CMS\fuel\modules\fuel\core\Loader.php
Line: 140
Function: load_file
File: C:\xampp\htdocs\FUEL-CMS\fuel\modules\fuel\models\Base_module_model.php
Line: 198
Function: helper
File: C:\xampp\htdocs\FUEL-CMS\fuel\modules\fuel\models\Fuel_users_model.php
Line: 49
Function: …
```
> Fix deprecated syntax in markdown_helper

- fuel/modules/fuel/core/MY_Model.php
formatters[1] like *_formatted or *_markdown weren't able to identify a `mediumtext` database field as type `string` and just skipped the method.
I couldn't find another way ($representatives or $formatters or represents in the field definition) to cast the field as type string. Jumping through the MY_Model::format() method lead me to this being the only valid way to getting the property formatted.
[1] https://docs.getfuelcms.com/general/models#formatters
> Detect `char` and `mediumtext` field types

- fuel/modules/fuel/assets/js/fuel/controller/BaseFuelController.js
Groups fieldset tabs as they appear in a form.
Needs plain fielsets `'k' => ['type' => 'fieldset', 'label' => 'Break out tabs'],` to break out of the tabs.
Made it work without updating jquery and made it future proof.
```
// https://stackoverflow.com/a/17809461/814031
if(!$.fn.addBack){
$.fn.addBack = $.fn.andSelf;
}
```
Description and proposal here: https://github.com/daylightstudio/FUEL-CMS/issues/569
> Multiple Fieldsets of Type `Tab` per Form
